# Generated by Django 4.0.4 on 2022-04-20 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbid',
            name='bid_holder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_bid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctioncomment',
            name='comment_author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
