# Generated by Django 4.0.4 on 2022-04-21 05:24

import auctions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionbid_bid_holder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='winner',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='bid_leader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(auctions.models.get_sentinel_user), related_name='bid_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.IntegerField(default=1),
        ),
    ]
