# Generated by Django 4.0.4 on 2022-04-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auctionlisting_winner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='current_bid',
            new_name='initial_bid',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='bid_leader',
        ),
    ]
