# Generated by Django 4.0.4 on 2022-04-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_current_bid_auctionlisting_initial_bid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='initial_bid',
            new_name='current_bid',
        ),
    ]
