# Generated by Django 4.0.4 on 2022-04-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_initial_bid_auctionlisting_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_bid',
        ),
        migrations.AlterField(
            model_name='auctionbid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
