# Generated by Django 4.0.4 on 2022-04-21 06:27

import auctions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_auctionlisting_current_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='auction_owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(auctions.models.get_sentinel_user), related_name='owned_auction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='auction_status',
            field=models.BooleanField(default=True),
        ),
    ]
