# Generated by Django 4.0.4 on 2022-04-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlisting_auction_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
