# Generated by Django 4.0.4 on 2022-04-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='category',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='auction_listing', to='auctions.auctioncategory'),
        ),
    ]
