# Generated by Django 4.0.4 on 2022-04-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_category_auctioncategory_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='category',
            new_name='category_name',
        ),
    ]
