# Generated by Django 4.0.4 on 2022-04-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_rename_category_auctionlisting_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='category_name',
            new_name='category',
        ),
    ]
