# Generated by Django 4.0.4 on 2022-04-23 03:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_rename_category_name_auctionlisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 4, 23, 3, 52, 56, 632397, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
