# Generated by Django 4.0.4 on 2022-04-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auctionlisting_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
